[package]
name = "multifactorials"
version = "0.1.0"
edition = "2021"
description = "A Rust crate who allows you to use multi factorials"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
